import type { Metadata } from 'next';
import './globals.css';

import { Providers } from '@/app/providers';
import { fonts } from '@/app/fonts';
import Nav from '@/app/nav';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={fonts.robotoMono.variable}>
      <body>
        <Providers>
          <Nav />
          {children}
        </Providers>
      </body>
    </html>
  );
}
